### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#234]
Too lazy to rename the subject.

https://boards.4chan.org/v/res/195566617
YouTube title not working; console:
"Linkify" crashed on Post No.195581883 (/v/). TypeError: Cannot read property 'bSLTzQzxYHQ' of undefined
    at Object.Linkify.title (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7325:39)
    at Post.Linkify.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7142:19)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9881:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9857:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:251:14) script.js:10001
Main.logError script.js:10001
"Linkify" crashed on Post No.195582040 (/v/). TypeError: Cannot read property '03e-kKjko_U' of undefined
    at Object.Linkify.title (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7325:39)
    at Post.Linkify.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7142:19)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9881:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9857:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:251:14) script.js:10001
Main.logError script.js:10001
"Linkify" crashed on Post No.195582575 (/v/). TypeError: Cannot read property 'zah19RJJ2EQ' of undefined
    at Object.Linkify.title (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7325:39)
    at Post.Linkify.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7142:19)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9881:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9857:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:251:14) script.js:10001
Main.logError script.js:10001
"Linkify" crashed on Post No.195583602 (/v/). TypeError: Cannot read property '9AkDoen79vQ' of undefined
    at Object.Linkify.title (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7325:39)
    at Post.Linkify.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7142:19)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9881:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9857:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:251:14) script.js:10001
Main.logError script.js:10001

Hover over crosslink not working in https://boards.4chan.org/q/res/651318, console:

Uncaught SyntaxError: Unexpected end of input script.js:2289
Get.fetchedPost script.js:2289
(anonymous function) script.js:2242
(anonymous function) script.js:320
Get.postClone script.js:2241
QuotePreview.mouseover script.js:3697

**Comment by ihavenoface** [comment]
Which version of 4chan X are you using?

**Comment by ididntknowicoulddothatXD** [comment]
3.4.10

**Comment by ihavenoface** [comment]
I can see how the first error might happen. Please try https://ihavenoface.me/testing/crx.crx to verify.
As for the the second error, no idea. A new profile might help.

**Comment by ididntknowicoulddothatXD** [comment]
It seems to work, even has image hover behavior, I'm impressed. I'll post if errors show up.
