### ISSUE TITLE
Index broken on /g/

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#267]
New index seems to break on /g/; when I try to refresh it says "index refresh failed" and loading /g/ normally brings up the old pagelist. Clicking "next" brings me to /g/1, clicking it again doesn't work.

Console says:
Index failure: TypeError: Cannot set property 'disabled' of null
    at Object.Index.setPage (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:2392:32)
    at Object.Index.buildPagelist (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:2381:13)
    at Object.Index.parse (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:2479:20)
    at XMLHttpRequest.Index.load (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:2453:17) script.js:2457
Index.load

**Comment by ihavenoface** [comment]
Works fine on my end.
Can you try a new browser profile?

**Comment by ididntknowicoulddothatXD** [comment]
I created a new profile and it works now. 
But what could've caused it?

**Comment by ihavenoface** [comment]
It complained about an element not being found so I'm not sure. Probably some addon/setting that removed it.
