### ISSUE TITLE
4chan-x is straight busted 

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#273]
Image expansion, posting, embedding, and image search 

Everything isn't working

Just saw that any new replies added after you are in a thread have full functionality, but if the page itself is refreshed, all of the posts from that far back cease to work

Using chrome 

Console errors:
3
Uncaught TypeError: Cannot read property 'type' of null script.js:941
Parsing of Post No.221458240 failed. Post will be skipped. TypeError: Cannot read property 'title' of null
    at Post.parseFile (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10294:50)
    at new Post (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10220:12)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10914:24)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11017
Parsing of Post No.221459018 failed. Post will be skipped. TypeError: Cannot read property 'title' of null
    at Post.parseFile (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10294:50)
    at new Post (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10220:12)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10914:24)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11017
Parsing of Post No.221459181 failed. Post will be skipped. TypeError: Cannot read property 'title' of null
    at Post.parseFile (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10294:50)
    at new Post (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10220:12)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10914:24)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11017
Parsing of Post No.221459721 failed. Post will be skipped. TypeError: Cannot read property 'title' of null
    at Post.parseFile (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10294:50)
    at new Post (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10220:12)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10914:24)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11017
Parsing of Post No.221460185 failed. Post will be skipped. TypeError: Cannot read property '0' of null
    at Post.parseFile (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10297:82)
    at new Post (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10220:12)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10914:24)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11017
Parsing of Post No.221461581 failed. Post will be skipped. TypeError: Cannot read property 'title' of null
    at Post.parseFile (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10294:50)
    at new Post (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10220:12)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:10914:24)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11017
Failed to load resource http://www.google-analytics.com/collect?v=1&_v=j15&aip=1&a=1287420941&t=pag…6369838825&_u=cACCAE~&cid=418508754.1384559724&tid=UA-166538-1&z=345162789
3
Uncaught TypeError: Cannot read property 'type' of null script.js:941
Uncaught TypeError: Cannot read property 'YT' of null VM6837:16380
Failed to load resource http://static.4chan-ads.org/Advertisers/316c8fd5eb074a19ad520703581a9bf8.jpg
Failed to load resource http://static.4chan-ads.org/Advertisers/8b1062c29bf84b3988e2898cc4adf195.jpg
Failed to load resource http://static.4chan-ads.org/Advertisers/209c3e723e3e496fbfabb91b4706d1ad.jpg
3
Uncaught TypeError: Cannot read property 'thread' of undefined

**Comment by ihavenoface** [comment]
ce335e4d9ff7b22f53b58c4ea309964bd9bf1972
