### ISSUE TITLE
Keep getting "Quick Reply dialog creation crashed. TypeError: Cannot read property '1' of null" when trying to reply to a post

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#290]
Console errors

Failed to load resource http://static.4chan-ads.org/ados.js
"Link Titles" crashed on Post No.232544609 (/v/). TypeError: Cannot read property 'hQzDeEtbvME' of undefined
    at Object.LinkTitles.changeTitle (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7378:39)
    at Post.LinkTitles.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7369:22)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11404:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11365:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:269:14) script.js:11469
"Link Titles" crashed on Post No.232545594 (/v/). TypeError: Cannot read property 'opgKhJB9OJw' of undefined
    at Object.LinkTitles.changeTitle (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7378:39)
    at Post.LinkTitles.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7369:22)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11404:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11365:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:269:14) script.js:11469
3
Uncaught TypeError: Cannot read property 'type' of null script.js:943
Quick Reply dialog creation crashed. TypeError: Cannot read property '1' of null
    at Object.QR.dialog (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5313:72)
    at Object.QR.open (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5009:19)
    at HTMLAnchorElement.QR.quote (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5140:10) script.js:11469
Uncaught TypeError: Cannot read property 'isLocked' of undefined script.js:5141
Uncaught TypeError: Cannot read property 'YT' of null 232535637:16514
Quick Reply dialog creation crashed. TypeError: Cannot read property '1' of null
    at Object.QR.dialog (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5313:72)
    at Object.QR.open (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5009:19)
    at HTMLAnchorElement.QR.quote (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5140:10) script.js:11469
Uncaught TypeError: Cannot read property 'isLocked' of undefined script.js:5141
Quick Reply dialog creation crashed. TypeError: Cannot read property '1' of null
    at Object.QR.dialog (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5313:72)
    at Object.QR.open (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5009:19)
    at HTMLAnchorElement.QR.quote (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5140:10) script.js:11469
Uncaught TypeError: Cannot read property 'isLocked' of undefined script.js:5141
Quick Reply dialog creation crashed. TypeError: Cannot read property '1' of null
    at Object.QR.dialog (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5313:72)
    at Object.QR.open (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5009:19)
    at HTMLAnchorElement.QR.quote (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:5140:10) script.js:11469
Uncaught TypeError: Cannot read property 'isLocked' of undefined script.js:5141

**Comment by smcdude** [comment]
QR isn't working in V2 either.

**Comment by ihavenoface** [comment]
Thank you for reporting.

As for v2, I'll look into it tomorrow.

**Comment by ihavenoface** [comment]
Should be fixed. I rushed through the commits so this release will be buggy.
