### ISSUE TITLE
Backlinks staying after re-pressing their links

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#293]
![screenshot 2014-02-21 13 18 49](https://f.cloud.github.com/assets/3334149/2233060/0a98191c-9b25-11e3-9ed2-eb50ecce4a8d.png)

"Link Titles" crashed on Post No.232669272 (/v/). TypeError: Cannot read property 'HhT5qX-V6Vc' of undefined
    at Object.LinkTitles.changeTitle (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7502:39)
    at Post.LinkTitles.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7493:22)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11558:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11519:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:273:14)
"Link Titles" crashed on Post No.232672206 (/v/). TypeError: Cannot read property 'VvBsPFSUm14' of undefined
    at Object.LinkTitles.changeTitle (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7502:39)
    at Post.LinkTitles.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7493:22)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11558:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11519:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:273:14)
Uncaught ReferenceError: dontrepeat is not defined chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9219
Failed to load resource http://static.4chan-ads.org/ados.js
3
Uncaught TypeError: Cannot read property 'type' of null chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:947
Uncaught TypeError: Cannot read property 'YT' of null 232668914:16514
11
Uncaught ReferenceError: dontrepeat is not defined chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:9219

**Comment by linklonk** [comment]
The tab icons aren't working either

**Comment by specialeddy** [comment]
I can confirm that I am having the same problem. It seems to happen randomly. Refreshing the thread and trying to click the backlinks fixes the problem temporarily until it happens again 2 minutes later on another post. This isn't an "occasional" instance, this is happening very frequently.

![post](https://f.cloud.github.com/assets/6633539/2253317/aca78d08-9dbb-11e3-86f0-c9866baf2063.png)
![post2](https://f.cloud.github.com/assets/6633539/2253318/aec57320-9dbb-11e3-9c6d-75e94cd1d7a0.png)

**Comment by ihavenoface** [comment]
Fixed in unstable https://github.com/ihavenoface/4chan-x/commit/021aa1af963cf21d54c4573a7f737bb2c01bf3a0.
