### ISSUE TITLE
"experienced an error" message

### ISSUE THREAD

**Issue by UltraMagnus0** [ihavenoface/4chan-x#3]
4chan x told me to paste this here, so I am, here it is:
2.34.5
http://boards.4chan.org/tg/
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.82 Safari/537.1

TypeError: Cannot read property 'previousSibling' of null
    at FileInfo.node (chrome-extension://ihhokehpaghpcohlodffniandbhjngkd/script.js:3582:25)
    at Object.Main.node (chrome-extension://ihhokehpaghpcohlodffniandbhjngkd/script.js:5565:13)
    at Main.ready (chrome-extension://ihhokehpaghpcohlodffniandbhjngkd/script.js:5459:12)
    at HTMLDocument.$.extend.ready.cb (chrome-extension://ihhokehpaghpcohlodffniandbhjngkd/script.js:323:16)

**Comment by ihavenoface** [comment]
https://github.com/MayhemYDG/4chan-x/issues/692
