### ISSUE TITLE
Linking a picture  not working

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#307]
Linking to an image's url is not working

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT http://static.4chan-ads.org/ados.js
"Link Titles" crashed on Post No.105180516 (/a/). TypeError: Cannot read property '6nSKkwzwdW4' of undefined
    at Object.LinkTitles.changeTitle (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7274:39)
    at Post.LinkTitles.node (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:7265:22)
    at Object.Main.callbackNodes (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11469:25)
    at Main.initReady (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:11430:14)
    at HTMLDocument.cb (chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:268:14) script.js:11534
3
Uncaught TypeError: Cannot read property 'type' of null script.js:947
Uncaught TypeError: Cannot read property 'YT' of null 105172775:16557
Uncaught TypeError: Array.prototype.indexOf called on null or undefined script.js:5156
2
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

**Comment by ihavenoface** [comment]
What do you mean by "Linking to an image's url is not working"?

The error is related to some issue in chromes storage api. It tries to grab the title of the video link from storage but for some reason it isn't loaded properly.

**Comment by linklonk** [comment]
![screenshot 2014-04-08 16 31 09](https://cloud.githubusercontent.com/assets/3334149/2648924/ce9253f4-bf5c-11e3-9b70-7af4fb10d1a6.png)

**Comment by ihavenoface** [comment]
For the other issue you'll have to disable Link Titles until it is fixed.

**Comment by ihavenoface** [comment]
v3.13.3 should be in the chrome webstore in about an hour. It should take of both problems.
